[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'dracula/vim'
name = 'dracula'
hook_add = '''
  let g:dracula_colorterm = 0
  colorscheme dracula
'''

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
  source ~/.config/nvim/rc/vim-airline.rc.vim
'''

[[plugins]]
repo = 'kristijanhusak/defx-icons'

[[plugins]]
repo = 'kristijanhusak/defx-git'

[[plugins]]
repo = 'Shougo/defx.nvim'
hook_add = '''
  source ~/.config/nvim/rc/defx.rc.vim
'''

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
  source ~/.config/nvim/rc/denite.rc.vim
'''

[[plugins]]
repo = 'qpkorr/vim-bufkill'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'neoclide/coc.nvim'
merged = 0
rev = 'release'
hook_add = '''
  source ~/.config/nvim/rc/coc.rc.vim
'''
