[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'dracula/vim'
name = 'dracula'
hook_add = '''
  let g:dracula_colorterm = 0
  syntax enable
  colorscheme dracula
'''

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
  lua require('plugins.vim-airline-conf')
'''

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'kristijanhusak/defx-icons'

[[plugins]]
repo = 'kristijanhusak/defx-git'

[[plugins]]
repo = 'Shougo/defx.nvim'
hook_add = '''
  lua require('plugins.defx-conf')
'''

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
  lua require('plugins.denite-conf')
'''

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'neoclide/coc.nvim'
merged = 0
rev = 'release'
hook_add = '''
  lua require('plugins.coc-conf')
'''
