[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Mofiqul/dracula.nvim'
hook_add = '''
  syntax enable
  colorscheme dracula
  highlight Normal ctermbg=NONE guibg=NONE
  highlight NonText ctermbg=NONE guibg=NONE
  highlight LineNr ctermbg=NONE guibg=NONE
  highlight Folded ctermbg=NONE guibg=NONE
  highlight EndOfBuffer ctermbg=NONE guibg=NONE
  highlight SignColumn ctermbg=NONE guibg=NONE
'''

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

[[plugins]]
repo = 'kyazdani42/nvim-tree.lua'
hook_add = '''
  lua require('plugins.nvim-tree-conf')
'''

[[plugins]]
repo = 'hoob3rt/lualine.nvim'
hook_add = '''
  lua require('plugins.lualine-conf')
'''

[[plugins]]
repo = 'akinsho/nvim-bufferline.lua'
hook_add = '''
  lua require('plugins.bufferline-conf')
'''

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'nvim-lua/popup.nvim'

[[plugins]]
repo = 'lewis6991/gitsigns.nvim'
depends = ['plenary.nvim']
hook_add = '''
  lua require('plugins.gitsigns-conf')
'''

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
depends = ['plenary.nvim', 'popup.nvim']
hook_add = '''
  lua require('plugins.telescope-conf')
'''

[[plugins]]
repo = 'neoclide/coc.nvim'
merged = 0
rev = 'release'
hook_add = '''
  lua require('plugins.coc-conf')
'''

# [[plugins]]
# repo = 'neovim/nvim-lspconfig'
# hook_add = '''
#   lua require('plugins.nvim-lspconfig-conf')
# '''
# 
# [[plugins]]
# repo = 'L3MON4D3/LuaSnip'
# 
# [[plugins]]
# repo = 'hrsh7th/nvim-compe'
# depends = ['LuaSnip']
# hook_add = '''
#   lua require('plugins.nvim-compe-conf')
# '''

